/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Roopik. All rights reserved.
 *  Licensed under the MIT License.
 *--------------------------------------------------------------------------------------------*/

/**
 * Component Types
 *
 * These types mirror the Core's component types.
 * They are used for type-safe communication between Extension and Core.
 */

/**
 * Component source type
 */
export type ComponentSource = 'ai-agent' | 'local-file' | 'drag-drop' | 'github' | 'manual';

/**
 * Component framework
 */
export type ComponentFramework = 'react' | 'vue' | 'svelte' | 'solid' | 'preact' | 'html';

/**
 * Component build state
 */
export type ComponentBuildState = 'pending' | 'building' | 'ready' | 'error';

/**
 * Component - Full component data
 */
export interface Component {
	/** Unique identifier (generated by Core) */
	id: string;

	/** Canvas this component belongs to */
	canvasId: string;

	/** Display name */
	name: string;

	/** Source type */
	source: ComponentSource;

	/** Detected framework */
	framework: ComponentFramework;

	/** Build state */
	buildState: ComponentBuildState;

	/** Last build error (if buildState === 'error') */
	lastBuildError?: BuildErrorInfo;

	/** Creation timestamp */
	createdAt: number;

	/** Last update timestamp */
	updatedAt: number;

	/**
	 * Position on canvas (managed by extension/webview)
	 * Note: width/height not stored - all sandboxes use DEFAULT_CONFIG dimensions
	 */
	position?: {
		x: number;
		y: number;
		zIndex?: number;
	};
}

/**
 * Source data for importing components
 */
export interface SourceData {
	type: ComponentSource;

	/** AI-generated code (for ai-agent source) */
	code?: string;

	/** Local file path (for local-file source) */
	filePath?: string;

	/** File name with extension (for drag-drop source) */
	fileName?: string;

	/** File content (for drag-drop source) */
	content?: string;

	/** GitHub URL (for github source) */
	githubUrl?: string;

	/** Manual files (for manual source) */
	files?: Record<string, string>;
	entryFile?: string;
}

/**
 * Request to create a component
 */
export interface CreateComponentRequest {
	/** Canvas to add component to */
	canvasId: string;

	/** Display name for the component */
	name: string;

	/** Source data */
	sourceData: SourceData;

	/** Initial position on canvas */
	position?: {
		x: number;
		y: number;
	};
}

/**
 * Build result (success case)
 */
export interface BuildResult {
	/** Bundled JavaScript code */
	bundledCode: string;

	/** CDN URLs for dependencies */
	cdnUrls: string[];

	/** Detected/used framework */
	framework: ComponentFramework;

	/** Resolved dependencies with versions */
	resolvedDependencies: Record<string, string>;

	/** Build time in milliseconds */
	buildTime: number;

	/** Bundle size in bytes */
	bundleSize: number;

	/** Path to the bundle file (for extension to read directly) */
	bundlePath?: string;
}

/**
 * Build error info (failure case)
 */
export interface BuildErrorInfo {
	/** Error message */
	message: string;

	/** Error code (for categorization) */
	code?: string;

	/** File that caused the error */
	file?: string;

	/** Line number */
	line?: number;

	/** Column number */
	column?: number;

	/** Stack trace */
	stack?: string;
}
