/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Roopik. All rights reserved.
 *  Licensed under the MIT License.
 *--------------------------------------------------------------------------------------------*/

/**
 * Component Pipeline V2 - Storage Types
 *
 * Defines all types related to storage operations for the component pipeline.
 * These types are used by both workspace storage (.roopik/) and app data storage (cache).
 */

// ============================================================================
// Source Files (Workspace Storage)
// ============================================================================

/**
 * Source files for a component
 * Key: filename (e.g., "Button.tsx", "styles.css")
 * Value: file content
 */
export type SourceFiles = Record<string, string>;

/**
 * Component metadata stored in meta.json
 */
export interface ComponentMeta {
	/** Unique component ID (also folder name) */
	id: string;

	/** Display name */
	name: string;

	/** How the component was created */
	source: ComponentSource;

	/** Additional source information (optional - manual components may not have this) */
	sourceInfo?: SourceInfo;

	/** Main entry file (relative, e.g., "Button.tsx") */
	entryFile: string;

	/** All source files (relative paths) */
	files: string[];

	/** Framework used (detected or specified) */
	framework: Framework;

	/** NPM dependencies with versions (empty {} if none) */
	dependencies: Record<string, string>;

	/** Hash of all source files (for cache invalidation) */
	contentHash: string;

	/** Creation timestamp */
	createdAt: number;

	/** Last update timestamp */
	updatedAt: number;
}

/**
 * How the component was created
 */
export type ComponentSource =
	| 'ai-agent'      // Generated by AI
	| 'local-file'    // Imported from user's project
	| 'github'        // Imported from GitHub
	| 'figma'         // Generated from Figma design
	| 'manual';       // Created manually by user

/**
 * Additional information about the component source
 */
export interface SourceInfo {
	// AI Agent
	promptId?: string;
	model?: string;

	// Local File
	originalPath?: string;

	// GitHub
	repoUrl?: string;
	filePath?: string;
	branch?: string;
	commitSha?: string;

	// Figma
	figmaFileId?: string;
	nodeId?: string;
}

/**
 * Supported frameworks
 */
export type Framework = 'react' | 'vue' | 'svelte' | 'solid' | 'preact' | 'html';

// ============================================================================
// Build Cache (App Data Storage)
// ============================================================================

/**
 * Bundled output stored in app data cache
 */
export interface BundledOutput {
	/** Bundled JavaScript code (ready to run in sandbox) */
	bundledCode: string;

	/** Build metadata */
	buildMeta: BuildMeta;
}

/**
 * Build metadata stored in build.json
 */
export interface BuildMeta {
	/** Component ID this build belongs to */
	componentId: string;

	/** Canvas ID */
	canvasId: string;

	/** Hash of source files used for this build */
	sourceHash: string;

	/** CDN URLs for external dependencies */
	cdnUrls: string[];

	/** Build time in milliseconds */
	buildTime: number;

	/** Bundle size in bytes */
	bundleSize: number;

	/** When this build was created */
	builtAt: number;
}

// ============================================================================
// Canvas & Index Types
// ============================================================================

/**
 * Canvas information in registry (canvases.json)
 * Contains essential metadata for quick listing without reading individual meta.json files
 */
export interface CanvasInfo {
	id: string;
	name: string;
	createdAt: number;
	updatedAt: number;
}

/**
 * Canvas registry (.roopik/canvases/canvases.json)
 */
export interface CanvasIndex {
	canvases: CanvasInfo[];
}

/**
 * Component index entry (quick lookup without reading meta.json)
 */
export interface ComponentIndexEntry {
	name: string;
	framework: Framework;
	source: ComponentSource;
	entryFile: string;
	buildState: BuildState;
	contentHash: string;
	createdAt: number;
	updatedAt: number;
}

/**
 * Component registry (.roopik/canvases/{id}/components/index.json)
 */
export interface ComponentIndex {
	components: Record<string, ComponentIndexEntry>;
}

/**
 * Build state for a component
 */
export type BuildState =
	| { status: 'pending' }
	| { status: 'building' }
	| { status: 'ready' }
	| { status: 'error'; error: string };

// ============================================================================
// Workspace Config
// ============================================================================

/**
 * Workspace configuration (.roopik/config.json)
 */
export interface WorkspaceConfig {
	/** Config version for migrations */
	version: number;

	/** Default canvas to open */
	defaultCanvas: string;

	/** Workspace settings */
	settings: {
		/** Auto-build on file change */
		autoBuild: boolean;

		/** Watch for file changes */
		watchFiles: boolean;

		/** CDN provider for dependencies */
		cdnProvider: 'esm.sh' | 'skypack' | 'unpkg';
	};
}

/**
 * Default workspace configuration
 */
export const DEFAULT_WORKSPACE_CONFIG: WorkspaceConfig = {
	version: 1,
	defaultCanvas: 'main',
	settings: {
		autoBuild: true,
		watchFiles: true,
		cdnProvider: 'esm.sh'
	}
};
