/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Roopik. All rights reserved.
 *  Licensed under the MIT License.
 *--------------------------------------------------------------------------------------------*/

import type { CSSInJSLibrary, CSSInJSDetectionResult } from '../../../common/cssResolvers/types.js';

/**
 * CSS-in-JS Detector
 *
 * Detects styles generated by CSS-in-JS libraries.
 * When detected, we redirect to the component file instead of trying
 * to find a CSS file (which doesn't exist for CSS-in-JS).
 *
 * Detection methods:
 * 1. Class name patterns (css-XXXXX for Emotion, sc-XXXXX for styled-components)
 * 2. Style tag attributes ([data-emotion], [data-styled])
 * 3. Stylesheet URL patterns (blob:, empty URL, virtual modules)
 *
 * When CSS-in-JS is detected:
 * - We skip source map resolution (no CSS file to map)
 * - We redirect to the component file (from data-roopik-source)
 * - User can edit styles in the component JSX/TSX file
 *
 * Supported libraries:
 * - Emotion (@emotion/react, @emotion/styled)
 * - styled-components
 * - Linaria
 * - vanilla-extract
 * - Stitches
 */
export class CSSInJsDetector {

	// Class name patterns for different libraries
	// These patterns match the generated class name formats used by each library
	private readonly classPatterns: Array<{
		library: CSSInJSLibrary;
		pattern: RegExp;
		priority: number; // Lower = higher priority (more specific)
	}> = [
		// Emotion: css-XXXXXX (7+ alphanumeric chars after css-)
		{
			library: 'emotion',
			pattern: /\bcss-[a-z0-9]{7,}\b/i,
			priority: 1
		},
		// styled-components: sc-XXXXX-X (component name hash)
		{
			library: 'styled-components',
			pattern: /\bsc-[a-zA-Z][a-zA-Z0-9]*-[a-zA-Z0-9]+\b/,
			priority: 1
		},
		// styled-components: short form sc-XXXXX
		{
			library: 'styled-components',
			pattern: /\bsc-[a-zA-Z]{2,}[a-zA-Z0-9]*\b/,
			priority: 2
		},
		// Linaria: uses short class names with hash
		{
			library: 'linaria',
			pattern: /\b[a-z][a-z0-9]{5,7}_[a-z0-9]+\b/i,
			priority: 2
		},
		// vanilla-extract: namespace_hash format
		{
			library: 'vanilla-extract',
			pattern: /\b[a-z]+_[a-z0-9]{7,}\b/i,
			priority: 2
		},
		// Stitches: s_XXX format or c_XXX for components
		{
			library: 'stitches',
			pattern: /\b[sc]_[a-zA-Z0-9]+\b/,
			priority: 2
		},
		// Generic pattern for unknown CSS-in-JS (fallback)
		{
			library: 'other',
			pattern: /\b[a-z]{2,4}-[a-zA-Z0-9]{8,}\b/i,
			priority: 10
		}
	];

	// Style tag data attributes for library detection
	private readonly styleTagAttributes: Record<string, CSSInJSLibrary> = {
		'data-emotion': 'emotion',
		'data-styled': 'styled-components',
		'data-linaria': 'linaria',
		'data-vanilla-extract': 'vanilla-extract',
		'data-stitches': 'stitches'
	};

	/**
	 * Detect CSS-in-JS from element class names
	 *
	 * @param className - Element's className string
	 * @param componentFile - Component file from data-roopik-source (for redirect)
	 */
	detectFromClassName(
		className: string,
		componentFile?: string
	): CSSInJSDetectionResult {
		if (!className) {
			return { detected: false, confidence: 'low' };
		}

		// Sort by priority (lower = more specific = higher priority)
		const sortedPatterns = [...this.classPatterns].sort((a, b) => a.priority - b.priority);

		// Check each pattern
		for (const { library, pattern, priority } of sortedPatterns) {
			const match = className.match(pattern);
			if (match) {
				return {
					detected: true,
					library,
					generatedClassName: match[0],
					componentFile,
					confidence: priority <= 1 ? 'high' : priority <= 5 ? 'medium' : 'low'
				};
			}
		}

		return { detected: false, confidence: 'low' };
	}

	/**
	 * Detect CSS-in-JS from multiple class names
	 * Useful when an element has multiple classes and we want to detect all CSS-in-JS patterns
	 */
	detectAllFromClassName(className: string): CSSInJSDetectionResult[] {
		if (!className) {
			return [];
		}

		const results: CSSInJSDetectionResult[] = [];
		const classes = className.split(/\s+/);

		for (const cls of classes) {
			const result = this.detectFromClassName(cls);
			if (result.detected) {
				results.push(result);
			}
		}

		return results;
	}

	/**
	 * Detect CSS-in-JS by checking <style> tag attributes
	 *
	 * This method generates JavaScript to execute in the browser context
	 * to inspect style tags for CSS-in-JS library markers.
	 *
	 * @returns JavaScript code to execute via CDP Runtime.evaluate
	 */
	getStyleTagDetectionScript(): string {
		const attributesList = Object.keys(this.styleTagAttributes).map(attr => `'${attr}'`).join(', ');

		return `
			(function() {
				const cssInJsAttributes = [${attributesList}];
				const results = [];

				document.querySelectorAll('style').forEach(style => {
					for (const attr of cssInJsAttributes) {
						if (style.hasAttribute(attr)) {
							results.push({
								library: style.getAttribute(attr) || attr.replace('data-', ''),
								attribute: attr,
								content: style.textContent?.slice(0, 100) || ''
							});
						}
					}
				});

				return results;
			})()
		`;
	}

	/**
	 * Parse the result of style tag detection script
	 */
	parseStyleTagDetectionResult(scriptResult: unknown): CSSInJSDetectionResult[] {
		if (!Array.isArray(scriptResult)) {
			return [];
		}

		const results: CSSInJSDetectionResult[] = [];

		for (const info of scriptResult) {
			if (typeof info === 'object' && info !== null && 'library' in info) {
				const attrName = info.attribute as string;
				const library = this.styleTagAttributes[attrName] || 'other';

				results.push({
					detected: true,
					library,
					confidence: 'high'
				});
			}
		}

		return results;
	}

	/**
	 * Check if a stylesheet is likely from CSS-in-JS
	 *
	 * CSS-in-JS libraries typically:
	 * - Use blob: URLs (runtime-generated)
	 * - Use data: URLs (inline generated)
	 *
	 * NOTE: We're now LESS aggressive about filtering.
	 * Empty sourceURL with isInline=true could be a regular <style> tag in HTML,
	 * not necessarily CSS-in-JS. We should include these styles.
	 */
	isGeneratedStyleSheet(
		sourceURL: string | undefined,
		isInline: boolean
	): boolean {
		// Blob URLs are runtime-generated (definitely CSS-in-JS)
		if (sourceURL?.startsWith('blob:')) {
			return true;
		}

		// Data URLs are inline generated (definitely CSS-in-JS)
		if (sourceURL?.startsWith('data:')) {
			return true;
		}

		// NOTE: Empty sourceURL with isInline=true is NOT necessarily CSS-in-JS!
		// It could be a regular <style> tag in HTML. We should NOT filter these out.
		// The old logic was too aggressive and filtered all inline styles.

		return false;
	}

	/**
	 * Check if a selector looks like a CSS-in-JS generated selector
	 */
	isGeneratedSelector(selector: string): boolean {
		// Check against our class patterns
		for (const { pattern } of this.classPatterns) {
			if (pattern.test(selector)) {
				return true;
			}
		}

		// Also check for common patterns not covered above
		// Hash-based selectors are typically generated
		const hashPatterns = [
			/\.[a-z]{1,3}[a-z0-9]{6,}/i,  // .a1b2c3d4e5
			/\._[a-z0-9]{6,}/i,            // ._abc123
		];

		for (const pattern of hashPatterns) {
			if (pattern.test(selector)) {
				return true;
			}
		}

		return false;
	}

	/**
	 * Get the library name from a style tag's data attribute
	 */
	getLibraryFromAttribute(attributeName: string): CSSInJSLibrary | null {
		return this.styleTagAttributes[attributeName] || null;
	}

	/**
	 * Determine the best action for a detected CSS-in-JS style
	 *
	 * Returns guidance on where to redirect the user for editing
	 */
	getEditRedirect(
		detection: CSSInJSDetectionResult,
		componentFile?: string
	): { target: 'component' | 'unknown'; file?: string; reason: string } {
		if (!detection.detected) {
			return { target: 'unknown', reason: 'No CSS-in-JS detected' };
		}

		const file = componentFile || detection.componentFile;

		if (file) {
			return {
				target: 'component',
				file,
				reason: `Styles are defined with ${detection.library || 'CSS-in-JS'} in the component file`
			};
		}

		return {
			target: 'unknown',
			reason: `CSS-in-JS (${detection.library || 'unknown'}) detected but component file unknown`
		};
	}
}
